### ISSUE TITLE
Should consider ssh config

### ISSUE THREAD

**Issue by haraldpusch** [epiccastle/spire#14] opened 2020-02-26 18:33 UTC
I have some server specific configuration in my `~/.ssh/config` which seems to be ignored by spire.
Example config:
```
Host exampleHost
  HostName example-host.com
  Port 12345
  User exampleUser
  IdentityFile /home/user/.ssh/exampleKey
```
When using `spire -e '(ssh "exampleHost" (get-fact))'` I would expect the connection to succeed (as `ssh exampleHost` does) but spire aborts with an `UnknownHostException`.

In my experience, it is a pretty common use case to have server specific configuration - especially for port, user and identity file.

**Comment by retrogradeorbit** [comment] 2020-02-27 01:13
duplicate of #13

**Closed by retrogradeorbit** 2020-02-27 01:13 UTC
